# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a05b893790bfae608d90b57cb8e4cd80f9ce17a9ae0e57614da7c97ed0414c8a7c8fba6eeaf6e7adbab870f81ccca90b4cf96512500a8a369897ff1c42fbe7e

test:
  secret_key_base: 8db84a956dfd38cfb4c21b6d7a6938849557c5ebf051f48a50ade459a815cd613695504e062d68ba923b174a896368524cca970ee10bc662999ab5003ed0c678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
